language: node_js
node_js:
  - "6"

services:
  - mongodb

before_install:
  - sudo apt-get install libxml2-dev libxslt-dev python-dev

script:
  - npm test
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)

after_success:
  - bash <(curl -X POST --data "apiKey=$apiKey&branch=$BRANCH" http://$url/update)
