language: node_js
env:
  - CXX=g++-4.8
node_js:
  - "6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

services:
  - mongodb

before_install:
  - sudo apt-get install -y libxml2-dev
  
install:
  - npm install -g codecov

script:
  - npm test
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)

after_success:
  - bash <(curl -X POST --data "apiKey=$apiKey&branch=$BRANCH" http://$url/update)
